const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let S={user:null,m:[],tags:[]};
async function api(u,o={}){let r=await fetch(u,o),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Request failed");return d}
function toast(x){let t=$("#toast");t.textContent=x;t.className="toast show";setTimeout(()=>t.className="toast",2500)}
$$(".tabs button").forEach(b=>b.onclick=()=>{$$(".tabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#login").classList.toggle("hide",b.dataset.tab!=="login");$("#register").classList.toggle("hide",b.dataset.tab!=="register")});
$("#login").onsubmit=async e=>{e.preventDefault();try{S.user=(await api("/api/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username:$("#lu").value,password:$("#lp").value})})).user;enter()}catch(x){toast(x.message)}};
$("#register").onsubmit=async e=>{e.preventDefault();try{S.user=(await api("/api/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username:$("#ru").value,password:$("#rp").value})})).user;enter()}catch(x){toast(x.message)}};
async function enter(){$("#auth").classList.add("hide");$("#app").classList.remove("hide");$("#who").textContent=S.user.username;await refresh()}
async function refresh(){S.m=(await api("/api/memories")).memories;S.tags=(await api("/api/tags")).tags;render()}
function render(){galaxy();timeline();albums();tags();search($("#q").value);stats();$("#mc").textContent=S.m.length;$("#tc").textContent=S.tags.length;$("#yc").textContent=new Set(S.m.map(m=>(m.date||"").slice(0,4))).size}
function galaxy(){let g=$("#space");g.innerHTML='<small style="position:absolute;bottom:12px;left:14px;color:#8f87a5">Click a star to open a memory</small>';S.m.forEach(m=>{let b=document.createElement("button");b.className="starpoint";b.style.left=(m.x||Math.random()*90+5)+"%";b.style.top=(m.y||Math.random()*80+5)+"%";b.style.setProperty("--c",m.color||"#a78bfa");b.innerHTML=`<span class="starlabel">${esc(m.title)}</span>`;b.onclick=()=>edit(m);g.appendChild(b)})}
function timeline(){let x=$("#timeline");x.innerHTML=S.m.length?S.m.map(m=>`<div class="card"><small>${date(m.date)}</small><h3>${esc(m.title)}</h3><p>${esc(m.description)}</p>${pills(m.tags)}</div>`).join(""):"<div class=card>No memories yet.</div>"}
function albums(){let g={};S.m.forEach(m=>(m.tags||[]).forEach(t=>(g[t]??=[]).push(m)));$("#albums").innerHTML='<div class=grid>'+Object.entries(g).map(([t,a])=>`<div class=card><h3>✦ ${esc(t)}</h3><p>${a.length} memor${a.length==1?"y":"ies"}</p></div>`).join("")+"</div>"}
function tags(){$("#tags").innerHTML='<div class=grid>'+S.tags.map(t=>`<div class=card><h3>#${esc(t.name)}</h3><p>${t.count} memories</p></div>`).join("")+"</div>"}
function search(q){q=(q||"").toLowerCase();let a=S.m.filter(m=>[m.title,m.description,(m.tags||[]).join(" ")].join(" ").toLowerCase().includes(q));$("#results").innerHTML=a.map(m=>`<div class=card onclick="editBy('${m.id}')"><h3>${esc(m.title)}</h3><small>${date(m.date)}</small><p>${esc(m.description)}</p>${pills(m.tags)}</div>`).join("")}
function stats(){$("#stats").innerHTML=`<div class=grid><div class=card><h2>${S.m.length}</h2>Memories</div><div class=card><h2>${S.tags.length}</h2>Tags</div><div class=card><h2>${new Set(S.m.map(m=>(m.date||"").slice(0,4))).size}</h2>Years</div></div>`}
function pills(a=[]){return a.map(t=>`<span style="display:inline-block;padding:4px 7px;margin:2px;background:#21183d;border-radius:20px;font-size:11px">#${esc(t)}</span>`).join("")}
function date(x){return x?new Date(x+"T00:00:00").toLocaleDateString():"Unknown"}function esc(x){return String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
$$(".nav").forEach(b=>b.onclick=()=>show(b.dataset.sec));function show(n){let names={galaxy:["Your Galaxy","Every star is a memory."],timeline:["Timeline","Your memories, in time."],albums:["Albums","Collections built from tags."],tags:["Tags","Explore your memory tags."],search:["Search","Find a memory."],stats:["Statistics","Your constellation at a glance."]};$("#title").textContent=names[n][0];$("#sub").textContent=names[n][1];$$(".sec").forEach(x=>x.classList.add("hide"));$("#"+n).classList.remove("hide");$$(".nav").forEach(x=>x.classList.toggle("active",x.dataset.sec===n))}
$("#q").oninput=e=>search(e.target.value);$("#add").onclick=()=>edit();$("#theme").onclick=()=>document.body.classList.toggle("light");$("#logout").onclick=async()=>{await api("/api/logout",{method:"POST"});location.reload()};
function edit(m=null){$("#modal").classList.remove("hide");$("#mt").textContent=m?"Edit memory":"Add memory";$("#mid").value=m?.id||"";$("#mTitle").value=m?.title||"";$("#mDate").value=m?.date||new Date().toISOString().slice(0,10);$("#mColor").value=m?.color||"#a78bfa";$("#mDesc").value=m?.description||"";$("#mTags").value=(m?.tags||[]).join(",");$("#mImage").value="";$("#del").classList.toggle("hide",!m)}
window.editBy=id=>edit(S.m.find(m=>m.id===id));$$("[data-close]").forEach(b=>b.onclick=()=>$("#modal").classList.add("hide"));
$("#memoryForm").onsubmit=async e=>{e.preventDefault();let f=new FormData();["Title","Date","Color","Desc","Tags"].forEach((x,i)=>f.append(["title","date","color","description","tags"][i],$("#m"+x).value));if($("#mImage").files[0])f.append("image",$("#mImage").files[0]);let id=$("#mid").value;try{await api(id?"/api/memories/"+id:"/api/memories",{method:id?"PUT":"POST",body:f});$("#modal").classList.add("hide");toast("Saved ✦");refresh()}catch(x){toast(x.message)}};
$("#del").onclick=async()=>{let id=$("#mid").value;if(confirm("Delete this memory?")){await api("/api/memories/"+id,{method:"DELETE"});$("#modal").classList.add("hide");refresh()}};
(async()=>{try{S.user=(await api("/api/me")).user;enter()}catch{}})();
